- usArt_frontend/public/index.html
- usArt_frontend/src/components/landingPage.css
- usArt_frontend/src/components/loginForm.jsx
- usArt_frontend/src/components/navBar.css
- usArt_frontend/src/components/register.css
- usArt_frontend/src/components/registerForm.jsx
> U3 1 crear/actualizar página fe del register

- usArt_backend/catalog/models.py
- usArt_backend/catalog/urls.py
- usArt_backend/catalog/views.py
- usArt_backend/userprofile/serializers.py
- usArt_backend/userprofile/urls.py
- usArt_backend/userprofile/views.py
Endpoint busqueda hecho tanto para productos como para usuarios.
producto:
/catalog/filter/keywords&tag
donde tag = 0 para comisión, tag = 1 para obra de arte
artista:
/userprofile/filter/keywords
> U4-2 Crear metodo GET de busqueda en la base de datos segun keywords

- usArt_frontend/src/components/loginForm.jsx
- usArt_frontend/src/components/registerForm.jsx
Register and Login backend working correctly
> U 3 register backend

- usArt_backend/.idea/usArt_backend.iml
- usArt_backend/userprofile/serializers.py
- usArt_backend/userprofile/tests.py
- usArt_backend/userprofile/urls.py
- usArt_backend/userprofile/views.py
Post de Favoritos fet i passa test
> UR-5-1 crear post (autenticado) de favoritos de una publicación con el usuario

- usArt_backend/userprofile/tests.py
- usArt_backend/userprofile/urls.py
- usArt_backend/userprofile/views.py
Mètode GET acabat junt amb el test.
> UR-15-1 Crear get (autenticado) de la compra de arte

- usArt_backend/catalog/serializers.py
- usArt_backend/catalog/tests.py
- usArt_backend/catalog/urls.py
- usArt_backend/catalog/views.py
> AR-9-1 Crear GET de la lista de comisiones de una publicación

- usArt_backend/.idea/usArt_backend.iml
- usArt_backend/api/tests.py
- usArt_backend/api/views.py
Test unitarios del modulo de autentificación --> Carpeta `api`
> Refactor: Test unitarios del modulo de autentificación

- usArt_backend/userprofile/tests.py
- usArt_backend/userprofile/urls.py
- usArt_backend/userprofile/views.py
Crear post (autenticado) de la compra de la obra de arte.
Endpoint: 
purchases/
Se le tiene que pasar data y los atributos: 
data = {
'pub_id': pub.id,
'price': 100.0,
'user_id': user.id,
}
> UR-9-3 Crear post (autenticado) de la compra de la obra de arte

- usArt_backend/.idea/usArt_backend.iml
- usArt_backend/catalog/serializers.py
- usArt_backend/catalog/tests.py
- usArt_backend/catalog/urls.py
- usArt_backend/catalog/views.py
Finalitzat POST de comisió. Tots els test passen. 
La URL : api/catalog/user/commission/post/
Se li passa com a dades:
data = {
'user_id': user.id,
'pub_id': pub.id,
'description': 'descripcio prova'
}
> UR-4-2 Crear metodo POST (autentificado) para pedir comisión

- usArt_backend/.idea/usArt_backend.iml
- usArt_backend/userprofile/models.py
- usArt_backend/userprofile/serializers.py
- usArt_backend/userprofile/tests.py
- usArt_backend/userprofile/urls.py
- usArt_backend/userprofile/views.py
- Nuevo endpoint `api/userprofile/review-artist/`
- `POST` en la clase `ReviewUser` con su serializer `ReviewUserSerializer`
- Test unitarios de puntuar artista, y de error 401 si no está loggeado
> UR-1-2: POST de puntuar artista

- usArt_frontend/src/App.js
- usArt_frontend/src/components/Home.jsx
- usArt_frontend/src/components/explorer.jsx
- usArt_frontend/src/components/explorerStyles.css
- usArt_frontend/src/components/search.css
- usArt_frontend/src/components/search.jsx
-Cards overflow 
>Enter works on search
-Search updated
>Now you can search with key Enter
>Now comissions and art are searched together
>Inside you can filter between co, art or authors
>You can delete the filter you applied
> Deuda tecnica bug fixes

- usArt_backend/catalog/serializers.py
- usArt_backend/catalog/tests.py
- usArt_backend/catalog/views.py
- usArt_frontend/src/components/publicacion.css
- usArt_frontend/src/components/publicacion.jsx
Finalizada la user story UR-4. EL frontend funciona perfectamente. He creado el botón y el formulario para pedir que quieres al artista. Se guarda perfectamente.  Se comprueba tanto si el usuario esta logueado o no y si la descripción se encuentra vacía.
> UR-4-1 crear botón de comisionar y el formulario

- usArt_frontend/src/components/publicacion.jsx
Finalizado el botón. Muestra "Comprar" en caso de que sea una publicación para comprar y en el caso de que sea una comisión "Contactar"
> UR-9-1 Crear el botón de comprar arte en la publicación

- usArt_backend/userprofile/serializers.py
- usArt_backend/userprofile/tests.py
- usArt_backend/userprofile/urls.py
- usArt_backend/userprofile/views.py
endpoint del GET: `/api/useprofile/review-artist/<nombre_artista>`
Devuelve una respuesta con el formato:
```
{
'average': 5.0
}
```
> UR-1-3: GET de la media de las reviews de un autor

- usArt_backend/userprofile/serializers.py
- usArt_backend/userprofile/tests.py
- usArt_backend/userprofile/urls.py
- usArt_backend/userprofile/views.py
Creat get, delete i get list de favoritos.
get list i post: ./api/userprofile/fav/
data = {
'pub_id':  publication.id
}
get i delete: ./api/userprofile/get/delete/fav/<str:pub_id>
> UR-5-3 crear endpoints favoritos

- usArt_backend/userprofile/views.py
- usArt_frontend/src/components/publicacion.css
- usArt_frontend/src/components/publicacion.jsx
Afegit el botó de favoritos que es modifica al clicar-ho (un cor) i fa el post o el delete a la base de dades
> Ur-5-2 añadir botón de favoritos en la publicación

- usArt_backend/catalog/serializers.py
- usArt_backend/catalog/views.py
- usArt_frontend/src/components/profile.jsx
Creado un modal con el formulario para añadir servicios
Para proximas iteraciones seria interesante poner la opcion de varias imagenes y mejoras visuales
@rogeranyor
> Ar 2 1 crear botón de añadir servicio y formulario

- usArt_backend/catalog/views.py
- usArt_frontend/package-lock.json
- usArt_frontend/src/components/buzonChat.jsx
- usArt_frontend/src/components/publicacion.jsx
Working buttons on accept and deny comission
@jordiBujaldon @Manuel-AHA)
> AR-9-4-crear-botones-de-aceptardenegar-comisión

- usArt_backend/authentication/views.py
- usArt_frontend/src/components/buzonChat.jsx
- usArt_frontend/src/components/buzonGeneralStyle.css
> Bug fixing chat

- usArt_backend/catalog/serializers.py
- usArt_backend/catalog/tests.py
- usArt_backend/catalog/urls.py
- usArt_backend/catalog/views.py
Endpoint per eliminar una publicació fet i unit test fets i passats.
url:  ./catalog/delete/<str:pub_id>
> AR-5-1 Crear método DELETE para eliminar

- usArt_frontend/src/components/profile.jsx
- usArt_frontend/src/components/purchaseDetails.jsx
Popup para devolver hecho con textarea para indicar el motivo de la devolución.
Está muy chulo.
> UR-2-1 Añadir boton de devolver y popup

- usArt_backend/userprofile/serializers.py
- usArt_backend/userprofile/tests.py
- usArt_backend/userprofile/urls.py
- usArt_backend/userprofile/views.py
Finalizado el metodo PUT. Si ya lo esta lo elimina, sino lo crea.
- [ X] User story
> Finalitzat POST de Bloquejar. Tots els test passen

- .github/workflows/testing-dev.yml
- usArt_frontend/src/components/Home.jsx
- usArt_frontend/src/components/buzonGeneralStyle.css
- usArt_frontend/src/components/home.css
- usArt_frontend/src/components/navBar.jsx
- usArt_frontend/src/components/profile.css
- usArt_frontend/src/components/profile.jsx
- usArt_frontend/src/components/publicacion.jsx
Finalitzades les tasques de la AR-5
> User story ar 5

- usArt_backend/authentication/models.py
- usArt_backend/catalog/serializers.py
- usArt_backend/catalog/tests.py
- usArt_backend/catalog/urls.py
- usArt_backend/catalog/views.py
Creat els metodes pel model denuncia, tot testejat passant unit tests
url per get i post: ./api/catalog/complaint/get/post/<str:pub_id>
url per put i delete: ./api/catalog/complaint/put/delete/<str:complaint_id>
cos del post:
data = {
'reason': 'mnsdmgfbsdjghu nmg, zndgklsjdfli'
}
cos del put:
data = {
'status': 'AP'
}
> UR-8-2 Crear métodos para denuncias

- usArt_frontend/src/components/purchaseDetails.jsx
Al finalizar, se ejecuta un window.open con los texboxes llenados para que el usuario envie el inquiry.
> UR-2-2-Enviar correo con el pedido

- usArt_backend/authentication/views.py
- usArt_backend/catalog/serializers.py
- usArt_backend/catalog/tests.py
- usArt_backend/catalog/urls.py
- usArt_backend/catalog/views.py
He creado las urls y views para:
- Pujar: PUT /api/catalog/auction/bid/, con el body {'pub_id': <str:pub_id>, 'bid' <float:bid>}, devuelve los detalles de la puja
- Conseguir detalles de la subasta: GET /api/catalog/auction/get/<str:pub_id>, devuelve los detalles de la subasta y la publicación asociada.
- Conseguir las pujas actuales: GET /api/catalog/auction/bidlist/<str:pub_id>, devuelve una lista ordenada de las pujas actuales en pub id
> UR-7-2 crear backend subasta

- usArt_backend/userprofile/tests.py
- usArt_backend/userprofile/urls.py
- usArt_backend/userprofile/views.py
- usArt_frontend/src/components/profile.jsx
- usArt_frontend/src/components/publicacion.jsx
He hecho dos GET en backend para poder extraer  si un usuario esta bloqueado. Tanto si estoy en el perfil de uno como si estoy en el perfil del otro. En forntend he hecho que el botón cambie de block a unblock dependiendo de si este usuario esta bloqueado o no. Si blockeas a un usuario te pregunta si estas seguro pero cuando lo desbloqueas no. Que un usuario este bloqueado significa que este no podrà ni comprar ni contactar con el usuario que lo haya bloqueado (le saldrà una alerta de que este usuario lo tiene bloqueado).
> AR-6-2 Condicion para tener en cuenta usuario bloqueado

- usArt_backend/catalog/urls.py
- usArt_backend/catalog/views.py
añadido metodo put para actualizar publicacion en /api/catalog/manage/update/
> AR-4-1 crear metodo put para actualizar publicacion

- usArt_frontend/src/components/search.css
- usArt_frontend/src/components/search.jsx
Now when you seach you have a loader screen before the results are shown
Now it shows "Loading.." instead of 0 results and when if it don't get results it shows a text saying there is no results
@jordiBujaldon @Manuel-AHA)
> Usability-feature Loading feedback

- usArt_backend/catalog/views.py
- usArt_frontend/src/components/profile.jsx
- usArt_frontend/src/components/publicacion.css
- usArt_frontend/src/components/publicacion.jsx
Frontend conectado con el backend, ahora puedes actualizar las publicaciones
> AR-4-2 Añadir boton modificar publicacion

- usArt_backend/api/serializer.py
- usArt_frontend/src/components/publicacion.css
- usArt_frontend/src/components/publicacion.jsx
Lista de denuncias en publicaciones, visible solo para admin
Bombardeen Marruecos
> UR-8-4 Crear metodos lista denuncias

- usArt_backend/api/serializer.py
- usArt_frontend/src/components/publicacion.jsx
Frontend hecho de borrar publicacion como admin
> A-1-2 Crear front para borrar como admin una publicacion

- usArt_backend/api/serializer.py
- usArt_backend/userprofile/serializers.py
- usArt_frontend/src/components/profile.css
- usArt_frontend/src/components/profile.jsx
- usArt_frontend/src/context/authcontext.js
- Se ha añadido a `serializers.py` de la carpeta `api` un nuevo atributo en el token del usuario que es su status (`ALO` si no está baneado, `BAN` si lo está). 
- Solo se puede banear al usuario con un perfil de Administrador:
user: admin
password: admin
- Saldrá un botón debajo del perfil para banear donde añadirás un texto y banear al usuario
@Manuel-AHA @rogeranyor @IvanSierra99 @Topiksit0
> A-2-2: Funcionamiento banear usuario FE/BE

- usArt_frontend/src/components/explorer.jsx
- usArt_frontend/src/components/navBar.jsx
- usArt_frontend/src/components/search.jsx
> Fixed texts

- usArt_frontend/src/components/Auction.jsx
Hot fix, best bid was not updating
(Ejemplo: @jordiBujaldon @Manuel-AHA)
> Hot fix, best bid was not updating
